---
driver_plugin: vagrant

driver_config:
  require_chef_omnibus: 12.5

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

provisioner:
  name: chef_zero

suites:
- name: recursor
  run_list:
    - recipe[pdns::recursor]
  attributes: {}
- name: authoritative
  run_list:
    - recipe[pdns::authoritative]
    - recipe[test::records]
  attributes: {}
- name: authoritative_source
  run_list:
    - recipe[pdns::authoritative]
    - recipe[test::records]
  attributes:
    pdns:
      build_method: source
- name: authoritative_backend_mysql
  run_list:
    - recipe[test::mysql]
  attributes: {}
- name: authoritative_backend_pgsql
  run_list:
    - recipe[test::pgsql]
  attributes: {}
