---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.3

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: recursor
  run_list:
    - recipe[pdns::recursor]
  attributes: {}
- name: authoritative
  run_list:
    - recipe[pdns::authoritative]
  attributes: {}
- name: authoritative_source
  run_list:
    - recipe[pdns::authoritative]
  attributes:
    pdns:
      build_method: source
- name: backend_pgsql
  run_list:
    - recipe[postgresql]
    - recipe[pdns::authoritative]
  attributes:
    pdns:
      build_method: source
      authoritative:
        package:
          backends:
          - gpgsql
