---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
    attributes:
      apt:
        compile_time_update: true
  - name: bento/centos-7.2

suites:
  - name: recursor_package
    run_list:
      - recipe[apt::default]
      - recipe[pdns::default]
      - recipe[pdns_test::recursor]
    attributes:

  - name: recursor_source
    run_list:
      - recipe[apt::default]
      - recipe[pdns::default]
      - recipe[pdns_test::recursor]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: source

  - name: authoritative_bind_package
    run_list:
      - recipe[apt::default]
      - recipe[pdns::default]
      - recipe[pdns_test::bind_backend]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: package
        flavor: authoritative

  - name: authoritative_bind_source
    run_list:
      - recipe[apt::default]
      - recipe[pdns::default]
      - recipe[pdns_test::bind_backend]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: source
        flavor: authoritative

  - name: authoritative_pgsql_package
    run_list:
      - recipe[apt::default]
      - recipe[postgresql::server]
      - recipe[pdns::default]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: package
        flavor: authoritative
        authoritative:
          backends:
            - gpgsql
          config:
            launch: gpgsql
            include-dir: '/etc/powerdns/pdns.d'
      postgresql:
        password:
          postgres: wadus

  - name: authoritative_pgsql_source
    run_list:
      - recipe[apt::default]
      - recipe[postgresql::server]
      - recipe[pdns::load_schema_pg]
      - recipe[pdns::default]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: source
        flavor: authoritative
        authoritative:
          backends:
            - gpgsql
          config:
            launch: gpgsql
            gpgsql_dbname: 'powerdns'
            gpgsql_host: '127.0.0.1'
            gpgsql_user: 'pdns'
            gpgsql_password: 'test'
      postgresql:
        password:
          postgres: wadus

  - name: authoritative_pipe_package
    run_list:
      - recipe[apt::default]
      - recipe[pdns_test::pipe_backend]
      - recipe[pdns::default]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: package
        flavor: authoritative
        authoritative:
          backends:
            - pipe
          config:
            pipe_command: /var/tmp/backend.pl
            launch: pipe

  - name: authoritative_pipe_source
    run_list:
      - recipe[apt::default]
      - recipe[pdns_test::pipe_backend]
      - recipe[pdns::default]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: source
        flavor: authoritative
        authoritative:
          backends:
            - pipe
          config:
            pipe_command: /var/tmp/backend.pl
            launch: pipe

  - name: slave_package
    run_list:
      - recipe[apt::default]
      - recipe[pdns::default]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: package
        flavor: slave

  - name: slave_source
    run_list:
      - recipe[apt::default]
      - recipe[pdns::default]
    excludes:
      - bento/centos-7.2
    attributes:
      pdns:
        build_method: source
        flavor: slave
