---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.18.12-1

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04

suites:
- name: recursor
  run_list:
    - recipe[apt::default]
    - recipe[pdns::recursor]
  attributes: {}
- name: recursor_source
  run_list:
    - recipe[apt::default]
    - recipe[pdns::recursor]
  attributes:
    pdns:
      build_method: source
- name: authoritative
  run_list:
    - recipe[apt::default]
    - recipe[pdns::authoritative]
    - recipe[pdns_test::default]
  attributes:
    pdns:
      authoritative:
        package:
          backends:
            - pipe
        config:
          pipe_command: /tmp/backend.pl
          launch: pipe
- name: authoritative_source
  run_list:
    - recipe[apt::default]
    - recipe[pdns::authoritative]
    - recipe[pdns_test::default]
  attributes:
    pdns:
      build_method: source
      authoritative:
        package:
          backends:
            - pipe
        config:
          pipe_command: /tmp/backend.pl
          launch: pipe
- name: backend_pgsql
  run_list:
    - recipe[apt::default]
    - recipe[postgresql]
    - recipe[pdns::authoritative]
  attributes:
    pdns:
      build_method: source
      authoritative:
        package:
          backends:
          - gpgsql
