---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  # On CentOS 6, restart the 'postgres' database could fail the first time so
  # let's try twice before failing:
  # https://github.com/sous-chefs/postgresql/issues/421
  retry_on_exit_code:
    - 1
  max_retries: 2

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.2
  - name: debian-8.8
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: recursor-multi
    run_list:
      - recipe[pdns_test::inspec_dependencies]
      - recipe[pdns_test::recursor_install_multi]
    attributes:
  - name: authoritative-multi
    run_list:
      - recipe[pdns_test::inspec_dependencies]
      - recipe[pdns_test::authoritative_install_multi]
    attributes:
  - name: authoritative-postgres
    # On CentOS 6, restart the 'postgres' database could fail the first time so
    # let's try twice before failing:
    # https://github.com/sous-chefs/postgresql/issues/421
    excludes: [
      'centos-6.9' # for dokken
    ]
    run_list:
      - recipe[pdns_test::inspec_dependencies]
      - recipe[pdns_test::authoritative_install_single_postgres]
    attributes:
