---
driver_config:
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_ACCESS_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8

platforms:

- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    image: ubuntu-12-04-x64
    size: 512mb
    region: nyc3
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
    - recipe[apt]

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    image: ubuntu-14-04-x64
    size: 512mb
    region: nyc3
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
    - recipe[apt]

suites:
- name: source
  run_list:
    - recipe[pdns::source]
  attributes: {}
- name: recursor
  run_list:
    - recipe[pdns::recursor]
  attributes: {}
- name: server
  run_list:
    - recipe[pdns::server]
  attributes:
    apt:
      compile_time_update: true
    build-essential:
      compile_time: true
