---
driver:
  name: dokken
  privileged: true
  chef_version: 15

transport:
  name: dokken

provisioner:
  name: dokken
  # On CentOS 6, restart the 'postgres' database could fail the first time so
  # let's try twice before failing:
  # https://github.com/sous-chefs/postgresql/issues/421
  retry_on_exit_code:
    - 1
  max_retries: 2
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install dnsutils -y

  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
          - RUN /usr/bin/apt-get update
          - RUN /usr/bin/apt-get install dnsutils -y

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
          - RUN /usr/bin/apt-get update
          - RUN /usr/bin/apt-get install dnsutils -y

  - name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
          - RUN /usr/bin/apt-get update
          - RUN /usr/bin/apt-get install dnsutils -y

  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd
      intermediate_instructions:
          - RUN /usr/bin/apt-get update
          - RUN /usr/bin/apt-get install dnsutils -y
